### ISSUE TITLE
add statistics topic

### ISSUE THREAD

**Issue by Beliavsky** [nevillejackson/Fortran#1]
Thanks for uploading the codes. I have listed the repo [here](https://github.com/Beliavsky/Fortran-code-on-GitHub). I suggest adding the topic statistics in the About section.

**Comment by nevillejackson** [comment]
Hi,Thank you.I do not understand what you mean by "  adding the topic statistics"Github has no "topic" facility?Do you want me to make a subdirectory called " statistics"  ?Do you want me to mention statistics in README.md?I have further codes to uploadRegardsNevilleSent from Samsung tablet.
-------- Original message --------From: Beliavsky ***@***.***> Date: 21/1/22  9:53 am  (GMT+10:00) To: nevillejackson/Fortran ***@***.***> Cc: Subscribed ***@***.***> Subject: [nevillejackson/Fortran] add statistics topic (Issue #1) 
Thanks for uploading the codes. I have listed the repo here. I suggest adding the topic statistics in the About section.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/nevillejackson/Fortran/issues/1",
"url": "https://github.com/nevillejackson/Fortran/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Beliavsky** [comment]
On the main page of your repo, click the icon to the right of About. That opens a box called Topics, where you could enter "statistics". The process is also described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .
